apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: payments
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: payments
spec:
  ports:
    - name: http
      nodePort: 31235
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: payments
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort