apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: payments
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payments
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo/payment-service?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: payments-service-native:latest
          imagePullPolicy: IfNotPresent
          name: payments
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP