---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8081"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: d841583867483610ac56d1167137d242e41742b7
    app.quarkus.io/build-timestamp: 2021-11-23 - 16:34:48 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: notification
spec:
  ports:
    - name: http
      nodePort: 31565
      port: 80
      targetPort: 8081
  selector:
    app.kubernetes.io/name: notification
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "8081"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: d841583867483610ac56d1167137d242e41742b7
    app.quarkus.io/build-timestamp: 2021-11-23 - 16:34:48 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notification
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/scheme: http
        app.quarkus.io/commit-id: d841583867483610ac56d1167137d242e41742b7
        app.quarkus.io/build-timestamp: 2021-11-23 - 16:34:48 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
      labels:
        app.kubernetes.io/name: notification
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_REDIS_NOTIFICATIONS_HOSTS
              value: "redis://eventbus:6379"

          image: jakubf/notification:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: notification
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
