apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: billing
  name: billing
spec:
  ports:
    - name: http
      nodePort: 31236
      port: 80
      targetPort: 6060
  selector:
    app.kubernetes.io/name: billing
  type: NodePort