apiVersion: v1
kind: Service
metadata:
  name: user-info-js
spec:
  ports:
    - name: http
      nodePort: 31238
      port: 3001
      targetPort: 3000
  selector:
    app: user-info-js
  type: NodePort
#  clusterIP: None #diky tohoto se nam do DNS prida zaznam se jmenem... vsude se tak muzeme na tento deployemnt odkazovat timto jmenem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info-js
spec:
  selector:
    matchLabels:
      app: user-info-js
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-info-js
    spec:
      containers:
        - image: williamyeh/json-server
          command: [ "json-server",  "--watch", "db.json" ]
          name: user-info-js
          ports:
            - containerPort: 3000
              protocol: TCP
              name: user-info-js
