version: "3.8"

services:
  user-service:
    container_name: user-service
    image: user-service:latest
    build: .
    command: ["--watch", "/data/db.json"]
    ports:
      - '127.0.20.1:80:3000'
    volumes:
      - ./mock:/data
